name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npm install

      - run: npm run build
        env:
          VITE_GOOGLE_CLIENT_ID: 892388053123-4vf70onb2ndiudlfqhn4nnofq65k2j5m.apps.googleusercontent.com

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: speakup.mtomlinson.ca
